const int README_SIZE = 2461;
const unsigned char *README = 
"# spconnect\n\nConnects to a serial port from a Windows Terminal/Console.\nCopyright 2024 David Atkinson. MIT License. "
"\nAvailable from https://github.com/david47k/spconnect/\n\n## About\n\nThis program connects to a serial port from a Win"
"dows Console/Terminal.\n\nIt\'s a basic program, designed to be used directly from Windows Terminal, as an\nalternative "
"to e.g. PuTTY. It is tested on (and designed to work on) Windows 10.\n\n## Using the program\n\n### Configuring the seri"
"al port\n\nYou can specify baud rate etc. by first using the windows built-in `mode`\ncommand. Running \'mode\' by itsel"
"f will give you a list of serial ports.\nCommon baud rates: 300, 1200, 2400, 4800, 9600, 19200, 38400, 57600,\n115200, 2"
"30400, 460800, 921600. e.g.:\n\n`mode com1 baud=115200 parity=n data=8 stop=1 to=off xon=off odsr=off octs=off dtr=on rt"
"s=on`\n\nor\n\n`mode com1 115200,n,8,1`\n\n### Starting the program\n\nStart this program with the serial port as an arg"
"ument, along with any options. \ne.g.:\n\n`spconnect com1 -w 10000`\n\n### Options\n\n```\n  -h      --help             "
"  Full documentation.\n  -l      --local-echo         Enable local echo of characters typed.\n  -s      --system-codepag"
"e    Use system codepage instead of UTF-8.\n  -r      --replace-cr         Replace input CR (\\r) with newline (\\n).\n "
" -d      --disable-vt         Disable virtual terminal (VT) codes.\n  -w 100  --write-timeout 100  Serial port write tim"
"eout, in ms. Default 1000.\n```\n\n### Quitting\n\nUse `Ctrl-F10` to quit.\n\n### Using a different codepage\n\nThe defa"
"ult is to use UTF-8 for console input and output. You can use the system\ncodepage instead by using the `-s` option. You"
" can check the system codepage \nand change it using the the windows built-in `mode con cp` command. e.g.:\n\n`mode con "
"cp select=1251`\n\n### Disable VT processing (raw mode)\n\nThe default is to process VT commands from both the keyboard "
"and the serial \nport. You can disable VT processing (essentially a raw mode) using `-d`.\n\n## Similar programs\n\n- [h"
"ttps://github.com/fasteddy516/SimplySerial](SimpleSerial) (C#, MIT license)\n- [https://github.com/YaSuenag/SimpleCom](S"
"impleCom) (C++, GPLv2 license)\n- [https://github.com/Dasors/comPST/tree/main](comPST) (PowerShell)\n- [https://github.c"
"om/airbornesurfer/windows-serial-terminal](windows-serial-terminal) (Python)\n- [https://github.com/weltling/convey](con"
"vey) (C++). Works with named pipes too.\n- [https://github.com/itas109/CommLite](CommLine) (C++). Serial port tool, TUI,"
" multi-platform.\n";
