const int README_SIZE = 2709;
const unsigned char *README = 
"# spconnect\n\nConnects to a serial port from a Windows Terminal/Console.\nCopyright 2024 David Atkinson. MIT License. "
"\nAvailable from https://github.com/david47k/spconnect/\n\n## About\n\nThis program connects to a serial port from a Win"
"dows Console/Terminal.\n\nIt\'s a basic program, designed to be used directly from Windows Terminal, as an\nalternative "
"to e.g. PuTTY. It is tested on (and designed to work on) Windows 10.\n\n## Using the program\n\n### Configuring the seri"
"al port\n\nYou can specify baud rate and 8 data bits, no parity, 1 stop bit, by using the\n`-c` option. e.g.:\n\n`spconn"
"ect com1 -c 9600`\n\nCommon baud rates: 300, 1200, 2400, 4800, 9600, 19200, 38400, 57600,\n115200, 230400, 460800, 92160"
"0.\n\nFor more complicated configuration, you can specify baud rate etc. by first\nusing the windows built-in `mode` com"
"mand. e.g.:\n\n`mode com1 baud=115200 parity=n data=8 stop=1 to=off xon=off odsr=off octs=off dtr=on rts=on`\n\nor\n\n`m"
"ode com1 115200,n,8,1`\n\nRunning `mode` by itself will give you a list of serial ports. \n\n### Starting the program\n"
"\nStart this program with the serial port as an argument, along with any options. \ne.g.:\n\n`spconnect com1 -w 10000`\n"
"\n### Options\n\n```\n  -h       --help               Full documentation.\n  -l       --local-echo         Enable local "
"echo of characters typed.\n  -s       --system-codepage    Use system codepage instead of UTF-8.\n  -r       --replace-c"
"r         Replace input CR (\\r) with newline (\\n).\n  -d       --disable-vt         Disable virtual terminal (VT) code"
"s.\n  -c 9600  --configure-port     Configure the port with given baud rate, 8N1.\n  -w 100   --write-timeout 100  Seria"
"l port write timeout, in ms. Default 1000.\n```\n\n### Quitting\n\nUse `Ctrl-F10` to quit.\n\n### Using a different code"
"page\n\nThe default is to use UTF-8 for console input and output. You can use the system\ncodepage instead by using the "
"`-s` option. You can check the system codepage \nand change it using the the windows built-in `mode con cp` command. e.g"
".:\n\n`mode con cp select=1251`\n\n### Disable VT processing (raw mode)\n\nThe default is to process VT commands from bo"
"th the keyboard and the serial \nport. You can disable VT processing (essentially a raw mode) using `-d`.\n\n## Similar "
"programs\n\n- [https://github.com/fasteddy516/SimplySerial](SimpleSerial) (C#, MIT license)\n- [https://github.com/YaSue"
"nag/SimpleCom](SimpleCom) (C++, GPLv2 license)\n- [https://github.com/Dasors/comPST/tree/main](comPST) (PowerShell)\n- ["
"https://github.com/airbornesurfer/windows-serial-terminal](windows-serial-terminal) (Python)\n- [https://github.com/welt"
"ling/convey](convey) (C++). Works with named pipes too.\n- [https://github.com/itas109/CommLite](CommLine) (C++). Serial"
" port tool, TUI, multi-platform.\n";
